# Generated by Django 4.1.6 on 2023-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=100)),
                ('patient_note', models.TextField(max_length=900)),
            ],
        ),
    ]
