# Generated by Django 4.1.6 on 2023-02-13 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9h', '9h'), ('10h', '10h'), ('11h', '11h'), ('12h', '12h'), ('14h', '14h'), ('15h', '15h'), ('16h', '16h'), ('17h', '17h')], default='3 PM', max_length=10),
        ),
    ]
