# Generated by Django 4.1.6 on 2023-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_date_appointment_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(default='', max_length=900),
        ),
    ]
